"""Parameter definitions for ContourGenerator."""

from __future__ import annotations

from plottter.generators.base import (
    BoolParam,
    ChoiceParam,
    FloatParam,
    IntParam,
    Parameter,
)


def build_parameters() -> list[Parameter]:
    return [
        ChoiceParam(
            name="mode",
            label="Mode",
            choices=["Contour Levels", "Line Art Trace", "Skeleton", "FMM Topographic"],
            default="Contour Levels",
            description="Contour Levels traces brightness isolines like a topographic map; Line Art Trace traces outlines of shapes from binary-thresholded images; Skeleton reduces thick strokes to single centerlines; FMM Topographic uses Fast Marching Method to produce wave-based topographic lines",
            choice_descriptions={
                "Contour Levels": "Traces isolines at multiple brightness thresholds — produces topographic-map-like concentric lines",
                "Line Art Trace": "Binarizes the image and traces the outlines of dark ink shapes — ideal for line drawings and logos",
                "Skeleton": "Reduces thick ink strokes to single-pixel centerlines via morphological thinning — produces one stroke per original line instead of two boundary outlines",
                "FMM Topographic": "Uses Fast Marching Method wave propagation to produce topographic contour lines — lines bunch in dark areas (slow wave) and spread in light areas (fast wave)",
            },
        ),
        # --- Contour Levels parameters ---
        IntParam(
            name="num_levels",
            label="Number of Contour Levels",
            min=2,
            max=64,
            step=1,
            default=8,
            visible_when={"mode": ["Contour Levels"]},
            description="Number of brightness levels at which to draw contour lines",
        ),
        ChoiceParam(
            name="spacing",
            label="Level Spacing",
            choices=["linear", "logarithmic", "quadratic"],
            default="linear",
            visible_when={"mode": ["Contour Levels"]},
            description="How contour levels are distributed across the brightness range",
            choice_descriptions={
                "linear": "Evenly-spaced levels — uniform density of lines across all brightness values",
                "logarithmic": "More levels in darker areas — emphasizes shadows and detail in dark regions",
                "quadratic": "More levels in midtones — good for photographs with gradual shading",
            },
        ),
        # --- Line Art Trace parameters ---
        IntParam(
            name="trace_threshold",
            label="Trace Threshold (0–255)",
            min=0,
            max=255,
            step=1,
            default=128,
            visible_when={"mode": ["Line Art Trace", "Skeleton"]},
            description="Brightness threshold for binarizing the image (0–255) — pixels below this are treated as ink",
        ),
        IntParam(
            name="smooth_iterations",
            label="Smooth Iterations (Chaikin)",
            min=0,
            max=5,
            step=1,
            default=0,
            visible_when={"mode": ["Line Art Trace", "Skeleton", "FMM Topographic"]},
            description="Number of Chaikin smoothing passes — each pass rounds corners for more flowing, organic-looking strokes",
        ),
        IntParam(
            name="cleanup_kernel",
            label="Cleanup Kernel Size",
            min=0,
            max=10,
            step=1,
            default=0,
            visible_when={"mode": ["Skeleton"]},
            description="Morphological cleanup kernel size (0 = disabled). MORPH_CLOSE fills small gaps in ink, MORPH_OPEN removes noise specks. Values 2–5 are typical",
        ),
        FloatParam(
            name="merge_gap_mm",
            label="Fragment Merge Gap (mm)",
            min=0.0,
            max=5.0,
            step=0.1,
            default=0.5,
            visible_when={"mode": ["Skeleton"]},
            description="Maximum endpoint distance (mm) for merging nearby skeleton fragments — reduces pen lifts by connecting polylines whose endpoints are close. Set to 0 to disable",
        ),
        # --- Adaptive thresholding (Line Art Trace and Skeleton modes) ---
        BoolParam(
            name="adaptive_threshold",
            label="Adaptive Threshold",
            default=False,
            visible_when={"mode": ["Line Art Trace", "Skeleton"]},
            description="Use local adaptive Gaussian thresholding instead of a global value — handles uneven lighting, scanned pages, and phone photos of drawings where global threshold fails",
        ),
        FloatParam(
            name="adaptive_c",
            label="Adaptive C Constant",
            min=-20.0,
            max=20.0,
            step=0.5,
            default=5.0,
            visible_when={"mode": ["Line Art Trace", "Skeleton"], "adaptive_threshold": [True]},
            description="Constant subtracted from the local Gaussian-weighted mean — higher values are stricter (less ink detected), lower/negative values are more permissive",
        ),
        # --- FMM Topographic parameters ---
        IntParam(
            name="fmm_num_contours",
            label="Number of Contours",
            min=2,
            max=100,
            step=1,
            default=20,
            visible_when={"mode": ["FMM Topographic"]},
            description="Number of isocontour levels to extract from the FMM travel-time field",
        ),
        ChoiceParam(
            name="fmm_source_point",
            label="Source Point",
            choices=["Center", "Custom", "Top Edge", "Bottom Edge", "Left Edge", "Right Edge"],
            default="Center",
            visible_when={"mode": ["FMM Topographic"]},
            description="Origin of the FMM wave. Center/Custom radiate from a point; the Edge sources seed the whole edge so the wave enters as straight lines that bunch and 'hug' dark regions as they advance",
            choice_descriptions={
                "Center": "Wave propagates from the center of the image",
                "Custom": "Wave propagates from a user-defined source point (set via point-click on the image)",
                "Top Edge": "Wave enters from the top as horizontal lines; they crowd and wrap around dark areas going down",
                "Bottom Edge": "Wave enters from the bottom as horizontal lines, crowding around dark areas going up",
                "Left Edge": "Wave enters from the left as vertical lines that hug dark areas",
                "Right Edge": "Wave enters from the right as vertical lines that hug dark areas",
            },
        ),
        FloatParam(
            name="fmm_source_x_pct",
            label="Source X (%)",
            min=-100.0,
            max=200.0,
            step=0.5,
            default=50.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_source_point": ["Custom"]},
            description="Horizontal position of FMM source as percentage of image width. Values outside 0–100 place the origin off the image — in Radial mode the rays then fan in from outside the frame",
        ),
        FloatParam(
            name="fmm_source_y_pct",
            label="Source Y (%)",
            min=-100.0,
            max=200.0,
            step=0.5,
            default=50.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_source_point": ["Custom"]},
            description="Vertical position of FMM source as percentage of image height. Values outside 0–100 place the origin off the image — in Radial mode the rays then fan in from outside the frame",
        ),
        FloatParam(
            name="fmm_gamma",
            label="Speed Gamma",
            min=0.1,
            max=20.0,
            step=0.1,
            default=1.0,
            visible_when={"mode": ["FMM Topographic"]},
            description="Gamma curve applied to the speed map — >1 concentrates lines in dark regions (slower propagation), <1 in light regions. High values strongly warp Radial-mode rays around image features",
        ),
        FloatParam(
            name="fmm_speed_floor",
            label="Speed Floor",
            min=0.001,
            max=1.0,
            step=0.005,
            default=0.01,
            visible_when={"mode": ["FMM Topographic"]},
            description="Minimum speed value to prevent infinite travel time in fully black areas — higher values reduce line density in very dark regions",
        ),
        ChoiceParam(
            name="fmm_contour_spacing",
            label="Contour Spacing",
            choices=["Linear", "Logarithmic", "Quadratic"],
            default="Linear",
            visible_when={"mode": ["FMM Topographic"]},
            description="Distribution of contour levels across the travel-time range",
            choice_descriptions={
                "Linear": "Evenly-spaced levels — uniform density of lines across the travel-time range",
                "Logarithmic": "More levels near the source — concentrates lines close to the wave origin",
                "Quadratic": "Denser levels farther from source — emphasizes the outer wave fronts",
            },
        ),
        FloatParam(
            name="fmm_min_contour_length_mm",
            label="Min Contour Length (mm)",
            min=0.0,
            max=20.0,
            step=0.5,
            default=2.0,
            visible_when={"mode": ["FMM Topographic"]},
            description="Minimum polyline length in mm — shorter contours are discarded as noise",
        ),
        # --- FMM Render Mode parameters ---
        ChoiceParam(
            name="fmm_render_mode",
            label="Render Mode",
            choices=["Contours", "Displacement", "Wave", "Radial"],
            default="Contours",
            visible_when={"mode": ["FMM Topographic"]},
            description="How to visualise the FMM travel-time field",
            choice_descriptions={
                "Contours": "Extract isocontour lines at evenly spaced travel-time levels (topographic map style)",
                "Displacement": "Draw parallel lines displaced perpendicularly by the T-field value — produces an engraving/relief effect",
                "Wave": "Draw horizontal scan lines whose sinusoidal amplitude is modulated by the T-field gradient magnitude",
                "Radial": "Draw lines emanating from the source point, following gradient ascent of T (perpendicular to isocontours)",
            },
        ),
        # Shared for Displacement and Wave
        IntParam(
            name="fmm_num_lines",
            label="Number of Lines",
            min=10,
            max=500,
            step=10,
            default=100,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Displacement", "Wave"]},
            description="Number of parallel lines (Displacement) or scan lines (Wave) to draw",
        ),
        # Displacement-specific
        FloatParam(
            name="fmm_displacement_mm",
            label="Max Displacement (mm)",
            min=0.1,
            max=20.0,
            step=0.1,
            default=5.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Displacement"]},
            description="Maximum perpendicular displacement of each line in mm — 0 = no displacement, higher values exaggerate the T-field relief",
        ),
        FloatParam(
            name="fmm_line_angle",
            label="Line Angle (°)",
            min=0.0,
            max=180.0,
            step=1.0,
            default=0.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Displacement"]},
            description="Angle of the parallel lines in degrees (0 = horizontal, 90 = vertical)",
        ),
        # Wave-specific
        FloatParam(
            name="fmm_amplitude_mm",
            label="Wave Amplitude (mm)",
            min=0.5,
            max=10.0,
            step=0.1,
            default=3.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"]},
            description="Maximum sinusoidal wave amplitude in mm — modulated by the T-field gradient magnitude at each point",
        ),
        FloatParam(
            name="fmm_frequency",
            label="Wave Frequency",
            min=1.0,
            max=50.0,
            step=0.5,
            default=10.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"]},
            description="Number of wave cycles across the canvas width — higher values produce more tightly packed waves",
        ),
        ChoiceParam(
            name="fmm_line_spacing",
            label="Line Spacing Mode",
            choices=["Uniform", "Adaptive", "Grouped", "Adaptive + Grouped"],
            default="Uniform",
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"]},
            description="Controls how scan-line Y positions are distributed across the drawing area",
            choice_descriptions={
                "Uniform": "Evenly spaced scan lines — classic wave pattern",
                "Adaptive": "Density follows gradient magnitude: dense where T changes rapidly (image detail), sparse in flat areas",
                "Grouped": "Lines appear in tight clusters separated by larger gaps — creates a banded effect",
                "Adaptive + Grouped": "Group gaps vary with gradient magnitude — clusters are denser in detailed areas",
            },
        ),
        FloatParam(
            name="fmm_min_spacing_mm",
            label="Min Spacing (mm)",
            min=0.1,
            max=10.0,
            step=0.1,
            default=0.5,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"], "fmm_line_spacing": ["Adaptive", "Adaptive + Grouped"]},
            description="Minimum spacing between scan lines in high-gradient (detailed) areas",
        ),
        FloatParam(
            name="fmm_max_spacing_mm",
            label="Max Spacing (mm)",
            min=0.5,
            max=20.0,
            step=0.5,
            default=5.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"], "fmm_line_spacing": ["Adaptive", "Adaptive + Grouped"]},
            description="Maximum spacing between scan lines in low-gradient (flat) areas",
        ),
        IntParam(
            name="fmm_group_size",
            label="Group Size",
            min=2,
            max=10,
            step=1,
            default=3,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"], "fmm_line_spacing": ["Grouped", "Adaptive + Grouped"]},
            description="Number of lines per group",
        ),
        FloatParam(
            name="fmm_group_gap_mm",
            label="Group Gap (mm)",
            min=1.0,
            max=20.0,
            step=0.5,
            default=4.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"], "fmm_line_spacing": ["Grouped"]},
            description="Gap between consecutive groups of scan lines",
        ),
        FloatParam(
            name="fmm_group_intra_spacing_mm",
            label="Intra-Group Spacing (mm)",
            min=0.1,
            max=5.0,
            step=0.1,
            default=0.5,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"], "fmm_line_spacing": ["Grouped", "Adaptive + Grouped"]},
            description="Spacing between individual lines within a group",
        ),
        FloatParam(
            name="fmm_displacement_variation",
            label="Displacement Variation",
            min=0.0,
            max=1.0,
            step=0.1,
            default=0.0,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Wave"]},
            description="Per-line random amplitude multiplier: 0 = all lines respond equally, 1 = dramatic variation between neighbouring lines",
        ),
        # Radial-specific
        IntParam(
            name="fmm_num_radials",
            label="Number of Radials",
            min=10,
            max=1000,
            step=10,
            default=120,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Radial"]},
            description="Number of radial lines evenly distributed around 360° from the source point — higher values give a denser starburst that renders image detail more clearly",
        ),
        FloatParam(
            name="fmm_step_size_mm",
            label="Step Size (mm)",
            min=0.1,
            max=2.0,
            step=0.05,
            default=0.5,
            visible_when={"mode": ["FMM Topographic"], "fmm_render_mode": ["Radial"]},
            description="Step size per iteration along the gradient — smaller values give smoother curves but take longer to compute",
        ),
        # --- Fill parameters (Line Art Trace mode only) ---
        ChoiceParam(
            name="fill",
            label="Fill Style",
            choices=["None", "Solid", "Hatching", "Cross-hatch", "Concentric"],
            default="None",
            visible_when={"mode": ["Line Art Trace"]},
            description="Fill style for enclosed contour shapes — None traces outlines only, other options fill the interior",
            choice_descriptions={
                "None": "Outline only — traces the boundary of each shape without filling the interior",
                "Solid": "Fills the interior with densely-packed parallel lines (spacing ~0.3mm for solid appearance)",
                "Hatching": "Fills with parallel lines at a configurable angle — produces a visible line texture inside the shape",
                "Cross-hatch": "Fills with two overlapping passes of hatching at perpendicular angles",
                "Concentric": "Fills with progressively smaller inward offsets of the contour shape — topographic map effect",
            },
        ),
        FloatParam(
            name="fill_spacing_mm",
            label="Fill Spacing (mm)",
            min=0.1,
            max=5.0,
            step=0.05,
            default=0.3,
            visible_when={"mode": ["Line Art Trace"], "fill": ["Solid", "Hatching", "Cross-hatch", "Concentric"]},
            description="Spacing between fill lines in millimeters (smaller = denser fill)",
        ),
        FloatParam(
            name="fill_angle",
            label="Fill Angle (°)",
            min=0.0,
            max=180.0,
            step=1.0,
            default=45.0,
            visible_when={"mode": ["Line Art Trace"], "fill": ["Hatching", "Cross-hatch"]},
            description="Angle of hatch fill lines in degrees (0 = horizontal, 45 = diagonal, 90 = vertical)",
        ),
        # --- Shared parameters (both modes) ---
        FloatParam(
            name="simplify_mm",
            label="Simplify Tolerance (mm)",
            min=0.0,
            max=5.0,
            step=0.1,
            default=0.3,
            description="RDP simplification tolerance in mm — reduces point count while preserving shape detail",
        ),
        BoolParam(
            name="smooth_curves",
            label="Smooth Curves (Bezier Fitting)",
            default=False,
            description="Fit cubic Bezier curves to the output polylines for smooth, organic-looking strokes",
        ),
        FloatParam(
            name="curve_tolerance_mm",
            label="Curve Tolerance (mm)",
            min=0.1,
            max=5.0,
            step=0.05,
            default=0.5,
            visible_when={"smooth_curves": [True]},
            description="How closely the fitted curves must follow the original points — lower = more faithful but more points",
        ),
        IntParam(
            name="trace_supersample",
            label="Trace Detail (Supersample)",
            min=1,
            max=4,
            step=1,
            default=1,
            visible_when={"mode": ["Contour Levels", "Line Art Trace"]},
            description="Upsamples the image before sub-pixel tracing for extra-smooth contours on low-resolution sources (1 = off). Higher values cost time and memory.",
        ),
        IntParam(
            name="min_contour_px",
            label="Min Contour Length (px)",
            min=3,
            max=500,
            step=1,
            default=10,
            description="Minimum contour length in pixels — shorter contours are discarded as noise",
        ),
        BoolParam(
            name="invert",
            label="Invert Image",
            default=False,
            description="Invert the image before processing",
        ),
        # Shared preprocessing parameters
        FloatParam(
            name="brightness",
            label="Brightness",
            min=-100.0,
            max=100.0,
            step=1.0,
            default=0.0,
            description="Adjust image brightness before processing (-100 to +100)",
        ),
        FloatParam(
            name="contrast",
            label="Contrast",
            min=-100.0,
            max=100.0,
            step=1.0,
            default=0.0,
            description="Adjust image contrast before processing (-100 to +100)",
        ),
        FloatParam(
            name="blur_radius",
            label="Blur Radius",
            min=0.0,
            max=20.0,
            step=0.5,
            default=1.0,
            description="Gaussian blur radius applied before processing — reduces noise and softens edges",
        ),
        FloatParam(
            name="x_offset_mm",
            label="X Offset (mm)",
            min=-500.0,
            max=500.0,
            step=0.5,
            default=0.0,
            randomizable=False,
            description="Horizontal offset applied to the generated output on the canvas page (mm)",
        ),
        FloatParam(
            name="y_offset_mm",
            label="Y Offset (mm)",
            min=-500.0,
            max=500.0,
            step=0.5,
            default=0.0,
            randomizable=False,
            description="Vertical offset applied to the generated output on the canvas page (mm)",
        ),
    ]
