"""Preset definitions for ContourGenerator."""

from __future__ import annotations

from plottter.generators.base import Preset


def build_presets() -> list[Preset]:
    return [
        Preset(
            name="Fine (16 levels)",
            params={
                "trace_supersample": 1,
                "mode": "Contour Levels",
                "num_levels": 16,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.2,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Coarse (6 levels)",
            params={
                "trace_supersample": 1,
                "mode": "Contour Levels",
                "num_levels": 6,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.5,
                "min_contour_px": 20,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 2.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Logarithmic (shadows detail)",
            params={
                "trace_supersample": 1,
                "mode": "Contour Levels",
                "num_levels": 10,
                "spacing": "logarithmic",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 10.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Inverted (highlights detail)",
            params={
                "trace_supersample": 1,
                "mode": "Contour Levels",
                "num_levels": 10,
                "spacing": "logarithmic",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": True,
                "brightness": 0.0,
                "contrast": 10.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="High Contrast Graphic",
            params={
                "trace_supersample": 1,
                # Quadratic level spacing emphasises midtone transitions;
                # extra contrast boost and heavier blur suit illustrations,
                # logos, and other graphics with flat colour regions.
                "mode": "Contour Levels",
                "num_levels": 12,
                "spacing": "quadratic",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.4,
                "min_contour_px": 15,
                "invert": False,
                "brightness": 0.0,
                "contrast": 30.0,
                "blur_radius": 2.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Portrait Photo",
            params={
                "trace_supersample": 1,
                # Many closely spaced levels with a gentle blur produce
                # fine topographic lines that reveal skin texture and
                # facial contours.  Logarithmic spacing gives more detail
                # in the shadows where most facial information lives.
                "mode": "Contour Levels",
                "num_levels": 20,
                "spacing": "logarithmic",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.2,
                "min_contour_px": 8,
                "invert": False,
                "brightness": 5.0,
                "contrast": 15.0,
                "blur_radius": 1.5,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Line Art / Trace",
            params={
                "trace_supersample": 1,
                # Optimised for clean B&W line drawings (icons, logos,
                # technical illustrations, hand-drawn sketches that have
                # been scanned and thresholded).
                #
                # Single threshold traces the outline of each ink region
                # at full pixel resolution; Chaikin smoothing (2 passes)
                # converts the pixel-stepped boundary into a smooth
                # plotter-friendly curve.  Small RDP tolerance preserves
                # detail; short-contour filter (min 5 px) removes noise
                # specks while keeping fine features.
                "mode": "Line Art Trace",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 2,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.15,
                "min_contour_px": 5,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 0.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Line Art / Solid Fill",
            params={
                "trace_supersample": 1,
                # Dense parallel lines fill each traced shape, producing a
                # solid appearance with tight 0.3 mm spacing (suitable for
                # 0.4–0.5 mm pens).  Outline is traced alongside the fill.
                "mode": "Line Art Trace",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 1,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "Solid",
                "fill_spacing_mm": 0.3,
                "fill_angle": 0.0,
                "simplify_mm": 0.2,
                "min_contour_px": 5,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 0.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Line Art / Hatched Fill",
            params={
                "trace_supersample": 1,
                # 45° hatching at 0.8 mm spacing gives a hand-drawn
                # crosshatch appearance inside each traced shape.
                "mode": "Line Art Trace",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 1,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "Hatching",
                "fill_spacing_mm": 0.4,
                "fill_angle": 45.0,
                "simplify_mm": 0.2,
                "min_contour_px": 5,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 0.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Line Art / Concentric Fill",
            params={
                "trace_supersample": 1,
                # Inward concentric rings trace the topology of each shape,
                # producing a topographic appearance inside traced regions.
                "mode": "Line Art Trace",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 1,
                "cleanup_kernel": 0,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "Concentric",
                "fill_spacing_mm": 0.4,
                "fill_angle": 45.0,
                "simplify_mm": 0.2,
                "min_contour_px": 5,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 0.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Skeleton / Center-line",
            params={
                "trace_supersample": 1,
                # Morphological skeletonization reduces thick strokes to
                # single-pixel-wide centerlines before tracing, producing
                # approximately one polyline per original ink line rather
                # than two parallel boundary outlines.  Recommended for
                # simple line art imports (logos, comics, ink drawings)
                # where a clean single-stroke output is desired.
                "mode": "Skeleton",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 1,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 5,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 0.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="Scanned Line Art",
            params={
                "trace_supersample": 1,
                # Adaptive thresholding handles scanned pages and phone
                # photos of drawings where global threshold fails due to
                # uneven lighting or shadow gradients.  Skeleton mode
                # produces clean centerlines from thick ink strokes.
                #
                # Tuned for maximum detail: smaller cleanup_kernel (1)
                # preserves thin pencil/pen lines that kernel=2 would
                # erase; reduced min_contour_px (4) keeps short strokes;
                # larger merge_gap (1.5 mm) reconnects broken fragments
                # from rough scan quality; two Chaikin passes smooth
                # the pixel-stepped skeleton into plotter-friendly curves.
                "mode": "Skeleton",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 2,
                "cleanup_kernel": 1,
                "merge_gap_mm": 1.5,
                "adaptive_threshold": True,
                "adaptive_c": 5.0,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.2,
                "min_contour_px": 4,
                "invert": False,
                "brightness": 5.0,
                "contrast": 15.0,
                "blur_radius": 0.5,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Portrait",
            params={
                "trace_supersample": 1,
                # Portrait-style FMM topographic lines — many closely
                # spaced contours with linear spacing reveal facial
                # contours and skin texture.  Invert is off so dark
                # regions (shadows) slow the wave and bunch lines there.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 1,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 15.0,
                "blur_radius": 1.5,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 30,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.5,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 3.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Detailed",
            params={
                "trace_supersample": 1,
                # Dense, engraving-like FMM topographic look: 200 contour
                # levels with gamma=0.4 lifting the midtones produces tight
                # line packing that preserves fine image structure across
                # the whole tonal range. No length filtering or smoothing
                # so even short contour fragments contribute texture.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.0,
                "min_contour_px": 0,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 1.5,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 200,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 0.4,
                "fmm_speed_floor": 0.02,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 0.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Landscape",
            params={
                "trace_supersample": 1,
                # Landscape / terrain style — fewer, well-separated contour
                # lines with logarithmic spacing emphasise the valleys
                # (dark regions) where contours bunch.  A gentle blur
                # smoothes out image noise before FMM propagation.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.4,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 10.0,
                "blur_radius": 2.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 15,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.02,
                "fmm_contour_spacing": "Logarithmic",
                "fmm_min_contour_length_mm": 5.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Dense Wave",
            params={
                "trace_supersample": 1,
                # Dense concentric wave pattern with many tightly packed
                # contours.  High gamma (2.0) strongly slows the wave in
                # dark areas, producing very dense line clusters there
                # while keeping bright areas relatively open.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 2,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.2,
                "min_contour_px": 5,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 50,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 2.0,
                "fmm_speed_floor": 0.005,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 1.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Depth Portrait",
            params={
                "trace_supersample": 1,
                # Use this preset with the "AI Depth Map" image source selected
                # in the image source controls — contour lines wrap around the
                # 3D structure of the face / subject rather than following
                # lighting boundaries.  Near objects (bright in depth map) slow
                # the wave so lines bunch up on the closest foreground subject.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 1,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 30,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.0,
                "fmm_speed_floor": 0.01,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 3.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Depth Landscape",
            params={
                "trace_supersample": 1,
                # Use this preset with the "AI Depth Map" image source and
                # "Invert" checked in the depth map source controls — wave
                # propagates fastest from near objects; distant terrain slows
                # the wave so contour lines bunch up on far-off hills and
                # mountains.  Logarithmic spacing adds extra detail near the
                # wave source for a terrain-map appearance.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.4,
                "min_contour_px": 10,
                "invert": True,
                "brightness": 0.0,
                "contrast": 0.0,
                "blur_radius": 1.5,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 0.7,
                "fmm_speed_floor": 0.02,
                "fmm_contour_spacing": "Logarithmic",
                "fmm_min_contour_length_mm": 5.0,
                "fmm_render_mode": "Contours",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Displacement Lines",
            params={
                "trace_supersample": 1,
                # Parallel lines displaced perpendicularly by the FMM
                # travel-time field — dark regions cause strong lateral
                # deflections, creating an engraving / relief effect.
                #
                # speed_floor=0.10 compresses T_range so midtones are
                # visible (≈3 mm deflection at b=0.5 with displacement=20).
                # With speed_floor=0.01 the effect was invisible for >90%
                # of photographic content (see prior analysis in task 106.1).
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 1.5,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.5,
                "fmm_speed_floor": 0.10,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_render_mode": "Displacement",
                "fmm_num_lines": 80,
                "fmm_displacement_mm": 20.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Wave Lines",
            params={
                "trace_supersample": 1,
                # Horizontal scan lines with sinusoidal amplitude modulated
                # by the FMM travel-time gradient magnitude — waves are large
                # in dark / high-gradient regions and flat in bright areas.
                #
                # speed_floor=0.10 gives usable gradient range across all
                # tones; amplitude=6 mm produces clearly visible sinusoids.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.5,
                "fmm_speed_floor": 0.10,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_render_mode": "Wave",
                "fmm_num_lines": 70,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 6.0,
                "fmm_frequency": 8.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Radial Lines",
            params={
                "trace_supersample": 1,
                # Lines radiate from canvas centre following gradient ascent
                # of the FMM travel-time field — a starburst that bends
                # around bright/dark features.
                #
                # Redesign (task 106.2): previous "blob in center" was caused
                # by speed_floor=0.01 creating extreme gradient spikes near
                # dark pixels, pulling all radials toward the same feature.
                # Fix: speed_floor=0.25 + gamma=0.8 smooth the field so lines
                # spread uniformly outward before deflecting around features.
                # Source is fixed at canvas centre for a clear starburst.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 2.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 0.8,
                "fmm_speed_floor": 0.25,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_render_mode": "Radial",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 3.0,
                "fmm_frequency": 10.0,
                "fmm_num_radials": 90,
                "fmm_step_size_mm": 1.0,
                "fmm_line_spacing": "Uniform",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Adaptive Wave",
            params={
                "trace_supersample": 1,
                # Scan lines with adaptive spacing and gradient-modulated
                # wave amplitude — lines cluster densely in high-gradient /
                # dark regions and spread apart in smooth / bright areas,
                # giving organic topographic density with visible sinusoids.
                #
                # speed_floor=0.10 ensures wave amplitude varies visibly
                # across all tones; wide spacing range (0.4–8 mm) produces
                # strong density variation between shadow and highlight.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.5,
                "fmm_speed_floor": 0.10,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_render_mode": "Wave",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 7.0,
                "fmm_frequency": 8.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Adaptive",
                "fmm_min_spacing_mm": 0.4,
                "fmm_max_spacing_mm": 8.0,
                "fmm_group_size": 3,
                "fmm_group_gap_mm": 4.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.0,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
        Preset(
            name="FMM Grouped Wave",
            params={
                "trace_supersample": 1,
                # Wave scan lines arranged in tight clusters of 4, separated
                # by large 10 mm gaps — strong inter-group whitespace makes
                # the grouping clearly visible, with per-line amplitude
                # variation giving a hand-drawn sketchy feel.
                #
                # speed_floor=0.10 ensures wave amplitude modulates visibly
                # across the full tonal range.  Wide group gap (10 mm)
                # versus tight intra-group spacing (0.5 mm) produces the
                # stacked-hatching / grouped-contour aesthetic.
                "mode": "FMM Topographic",
                "num_levels": 8,
                "spacing": "linear",
                "trace_threshold": 128,
                "smooth_iterations": 0,
                "cleanup_kernel": 0,
                "merge_gap_mm": 0.5,
                "adaptive_threshold": False,
                "adaptive_c": 5.0,
                "fill": "None",
                "fill_spacing_mm": 0.3,
                "fill_angle": 45.0,
                "simplify_mm": 0.3,
                "min_contour_px": 10,
                "invert": False,
                "brightness": 0.0,
                "contrast": 20.0,
                "blur_radius": 1.0,
                "smooth_curves": False,
                "curve_tolerance_mm": 0.5,
                "fmm_num_contours": 20,
                "fmm_source_point": "Center",
                "fmm_source_x_pct": 50.0,
                "fmm_source_y_pct": 50.0,
                "fmm_gamma": 1.5,
                "fmm_speed_floor": 0.10,
                "fmm_contour_spacing": "Linear",
                "fmm_min_contour_length_mm": 2.0,
                "fmm_render_mode": "Wave",
                "fmm_num_lines": 100,
                "fmm_displacement_mm": 5.0,
                "fmm_line_angle": 0.0,
                "fmm_amplitude_mm": 6.0,
                "fmm_frequency": 8.0,
                "fmm_num_radials": 120,
                "fmm_step_size_mm": 0.5,
                "fmm_line_spacing": "Grouped",
                "fmm_min_spacing_mm": 0.5,
                "fmm_max_spacing_mm": 5.0,
                "fmm_group_size": 4,
                "fmm_group_gap_mm": 10.0,
                "fmm_group_intra_spacing_mm": 0.5,
                "fmm_displacement_variation": 0.5,
                "x_offset_mm": 0.0,
                "y_offset_mm": 0.0,
            },
        ),
    ]
