"""Parameter definitions for the Sketch generator."""

from __future__ import annotations

from plottter.generators.base import (
    BoolParam,
    ChoiceParam,
    FloatParam,
    IntParam,
    Parameter,
)


def build_parameters() -> list[Parameter]:
    return [
        FloatParam(
            name="line_density",
            label="Line Density",
            min=0.1,
            max=5.0,
            step=0.1,
            default=1.0,
            description="Target density — higher = more lines, darker result",
        ),
        IntParam(
            name="line_max_limit",
            label="Max Line Segments",
            min=100,
            max=100_000,
            step=100,
            default=10_000,
            description="Maximum number of line segments",
        ),
        IntParam(
            name="line_length_px",
            label="Line Length (px)",
            min=5,
            max=100,
            step=1,
            default=20,
            description="Length of each line segment in pixels",
        ),
        IntParam(
            name="angle_tests",
            label="Angle Tests",
            min=4,
            max=72,
            step=1,
            default=36,
            description="Candidate directions tested per step — values <36 use evenly-spaced angles; ≥36 tests all integer points on a Bresenham circle (full pixel-resolution coverage)",
        ),
        # --- squiggle params ---
        IntParam(
            name="squiggle_min_length",
            label="Squiggle Min Length",
            min=1,
            max=100,
            step=1,
            default=3,
            description="Minimum number of segments a squiggle must have to be kept",
        ),
        IntParam(
            name="squiggle_max_length",
            label="Squiggle Max Length",
            min=5,
            max=500,
            step=1,
            default=50,
            description="Maximum number of segments per squiggle",
        ),
        FloatParam(
            name="squiggle_max_deviation",
            label="Squiggle Max Deviation",
            min=0.0,
            max=100.0,
            step=1.0,
            default=25.0,
            description="How far into bright areas a squiggle can go before stopping — higher = longer squiggles",
        ),
        # --- erase params ---
        IntParam(
            name="erase_min",
            label="Erase Min",
            min=1,
            max=100,
            step=1,
            default=1,
            description="Minimum erase amount applied at dark pixels — small = many fine strokes in shadows",
        ),
        IntParam(
            name="erase_max",
            label="Erase Max",
            min=10,
            max=255,
            step=1,
            default=100,
            description="Maximum erase amount applied at bright pixels — large = bright areas quickly used up",
        ),
        IntParam(
            name="erase_radius_min",
            label="Erase Radius Min (px)",
            min=1,
            max=10,
            step=1,
            default=1,
            description="Erase radius at dark pixels — smaller = finer strokes in shadows",
        ),
        IntParam(
            name="erase_radius_max",
            label="Erase Radius Max (px)",
            min=1,
            max=20,
            step=1,
            default=4,
            description="Erase radius at bright pixels — larger = wider brightening in highlights",
        ),
        FloatParam(
            name="tone",
            label="Tone Curve",
            min=0.0,
            max=1.0,
            step=0.05,
            default=0.5,
            description="Blends linear (0) and cubic (1) easing — higher = more contrast between dark/bright erase amounts",
        ),
        # --- directionality / edge params ---
        FloatParam(
            name="directionality",
            label="Directionality",
            min=0.0,
            max=100.0,
            step=1.0,
            default=0.0,
            description="Follow natural contours — higher values push lines along directions of lowest brightness variance",
        ),
        FloatParam(
            name="edge_power",
            label="Edge Power",
            min=0.0,
            max=100.0,
            step=1.0,
            default=0.0,
            description="Attract lines toward detected edges",
        ),
        IntParam(
            name="max_pixel_coverage",
            label="Max Pixel Coverage",
            min=1,
            max=10,
            step=1,
            default=2,
            description="Maximum times a pixel can be used by accepted paths — prevents over-inking",
        ),
        FloatParam(
            name="max_overlap_ratio",
            label="Max Overlap Ratio",
            min=0.0,
            max=1.0,
            step=0.05,
            default=0.55,
            description="Reject paths where this fraction of pixels already have ink",
        ),
        IntParam(
            name="coverage_radius",
            label="Coverage Radius (px)",
            min=0,
            max=5,
            step=1,
            default=1,
            description="Pixel radius to reserve around accepted paths",
        ),
        BoolParam(
            name="continuous",
            label="Continuous",
            default=True,
            description="Chain strokes into continuous paths — fewer pen lifts",
        ),
        IntParam(
            name="chain_max",
            label="Chain Max",
            min=1,
            max=50,
            step=1,
            default=18,
            description="Maximum segments chained without pen lift",
        ),
        FloatParam(
            name="long_line_bias",
            label="Long Line Bias",
            min=0.0,
            max=1.0,
            step=0.05,
            default=0.5,
            description="Probability of random long-line bonus in dark areas — 0 = uniform length, 1 = frequent long strokes",
        ),
        FloatParam(
            name="straight_bias",
            label="Straight Bias",
            min=0.0,
            max=1.0,
            step=0.05,
            default=0.7,
            description="Tendency to maintain stroke direction — higher = more flowing parallel strokes",
        ),
        BoolParam(
            name="multi_pass",
            label="Multi-Pass",
            default=True,
            description="Use 3-pass generation with varying stroke profiles — long strokes first, fine detail last",
        ),
        # --- standard image preprocessing params ---
        BoolParam(
            name="invert",
            label="Invert Image",
            default=False,
            description="Invert the image (dark and bright areas swap roles)",
        ),
        FloatParam(
            name="brightness",
            label="Brightness",
            min=-100.0,
            max=100.0,
            step=1.0,
            default=0.0,
            description="Adjust image brightness before processing (-100 to +100)",
        ),
        FloatParam(
            name="contrast",
            label="Contrast",
            min=-100.0,
            max=100.0,
            step=1.0,
            default=0.0,
            description="Adjust image contrast before processing (-100 to +100)",
        ),
        FloatParam(
            name="blur_radius",
            label="Blur Radius",
            min=0.0,
            max=20.0,
            step=0.5,
            default=1.0,
            description="Gaussian blur applied before processing — smooths brightness transitions",
        ),
        IntParam(
            name="unsharp_amount",
            label="Unsharp Mask",
            min=0,
            max=5,
            step=1,
            default=2,
            description="Unsharp mask strength applied after blur — 0 = disabled, higher = sharper edges",
        ),
        # --- offset params ---
        FloatParam(
            name="x_offset_mm",
            label="X Offset (mm)",
            min=-500.0,
            max=500.0,
            step=0.5,
            default=0.0,
            randomizable=False,
            description="Horizontal offset applied to the generated output on the canvas page (mm)",
        ),
        FloatParam(
            name="y_offset_mm",
            label="Y Offset (mm)",
            min=-500.0,
            max=500.0,
            step=0.5,
            default=0.0,
            randomizable=False,
            description="Vertical offset applied to the generated output on the canvas page (mm)",
        ),
        ChoiceParam(
            name="mark_mode",
            label="Mark Mode",
            choices=["Squiggle Only", "Hybrid"],
            default="Squiggle Only",
            description="Squiggle Only: existing tracing only. Hybrid: pick best of squiggle, straight lines, hatch marks, and circles per seed.",
        ),
    ]
