"""Preset definitions for the Sketch generator."""

from __future__ import annotations

from plottter.generators.base import Preset


def build_presets() -> list[Preset]:
    _base = {
        "line_density": 1.0,
        "line_max_limit": 10_000,
        "invert": False,
        "brightness": 0.0,
        "contrast": 0.0,
        "blur_radius": 1.0,
        "unsharp_amount": 2,
        "squiggle_min_length": 3,
        "squiggle_max_length": 50,
        "squiggle_max_deviation": 25.0,
        "angle_tests": 36,
        "line_length_px": 20,
        "erase_min": 1,
        "erase_max": 100,
        "erase_radius_min": 1,
        "erase_radius_max": 4,
        "tone": 0.5,
        "directionality": 0.0,
        "edge_power": 0.0,
        "max_pixel_coverage": 2,
        "max_overlap_ratio": 0.55,
        "coverage_radius": 1,
        "continuous": True,
        "chain_max": 18,
        "long_line_bias": 0.5,
        "straight_bias": 0.7,
        "multi_pass": True,
        "x_offset_mm": 0.0,
        "y_offset_mm": 0.0,
        "mark_mode": "Squiggle Only",
    }
    return [
        # --- Quick / light presets (fast, good for preview) ---
        Preset(
            name="Quick Sketch",
            params={
                **_base,
                "line_max_limit": 3000,
                "angle_tests": 12,
                "line_length_px": 15,
                "squiggle_max_length": 30,
                "chain_max": 12,
                "multi_pass": False,
            },
            description="Fast preview — fewer lines, lower quality, good for testing settings",
        ),
        # --- Portrait / figure presets ---
        Preset(
            name="Portrait",
            params={
                **_base,
                "line_density": 1.5,
                "line_max_limit": 8000,
                "angle_tests": 16,
                "line_length_px": 15,
                "squiggle_max_length": 40,
                "squiggle_max_deviation": 20.0,
                "directionality": 30.0,
                "edge_power": 15.0,
                "straight_bias": 0.8,
                "long_line_bias": 0.3,
                "erase_radius_max": 3,
                "tone": 0.6,
                "unsharp_amount": 3,
                "chain_max": 20,
            },
            description="Optimized for faces and figures — follows contours, fine detail in features",
        ),
        Preset(
            name="Contour Portrait",
            params={
                **_base,
                "line_density": 1.2,
                "line_max_limit": 6000,
                "angle_tests": 16,
                "line_length_px": 18,
                "directionality": 60.0,
                "edge_power": 30.0,
                "straight_bias": 0.6,
                "squiggle_max_length": 60,
                "squiggle_max_deviation": 15.0,
                "long_line_bias": 0.2,
                "chain_max": 25,
                "unsharp_amount": 3,
                "tone": 0.7,
            },
            description="Strong contour following — lines trace along edges and features",
        ),
        # --- Dense / detailed presets ---
        Preset(
            name="Dense Ink",
            params={
                **_base,
                "line_density": 2.5,
                "line_max_limit": 15000,
                "angle_tests": 16,
                "line_length_px": 12,
                "squiggle_max_length": 25,
                "max_pixel_coverage": 4,
                "max_overlap_ratio": 0.7,
                "coverage_radius": 0,
                "erase_min": 1,
                "erase_max": 60,
                "erase_radius_min": 1,
                "erase_radius_max": 2,
                "tone": 0.3,
                "straight_bias": 0.5,
                "chain_max": 10,
            },
            description="Very dense coverage — many short strokes, dark result, good for high contrast images",
        ),
        Preset(
            name="Crosshatch",
            params={
                **_base,
                "line_density": 1.8,
                "line_max_limit": 8000,
                "angle_tests": 4,
                "line_length_px": 25,
                "squiggle_max_length": 15,
                "squiggle_max_deviation": 40.0,
                "straight_bias": 0.9,
                "long_line_bias": 0.6,
                "max_pixel_coverage": 3,
                "continuous": False,
                "erase_radius_max": 3,
            },
            description="Angular crosshatch pattern — 4 directions only, long straight strokes",
        ),
        # --- Loose / artistic presets ---
        Preset(
            name="Loose Sketch",
            params={
                **_base,
                "line_density": 0.6,
                "line_max_limit": 3000,
                "angle_tests": 12,
                "line_length_px": 25,
                "squiggle_max_length": 80,
                "squiggle_max_deviation": 50.0,
                "straight_bias": 0.85,
                "long_line_bias": 0.8,
                "chain_max": 35,
                "erase_radius_min": 2,
                "erase_radius_max": 6,
                "erase_min": 5,
                "erase_max": 120,
                "max_pixel_coverage": 1,
                "coverage_radius": 2,
            },
            description="Few long flowing strokes — sparse, gestural, hand-drawn feel",
        ),
        Preset(
            name="Scribble",
            params={
                **_base,
                "line_density": 1.0,
                "line_max_limit": 5000,
                "angle_tests": 8,
                "line_length_px": 10,
                "squiggle_max_length": 100,
                "squiggle_max_deviation": 60.0,
                "straight_bias": 0.3,
                "long_line_bias": 0.1,
                "chain_max": 40,
                "directionality": 10.0,
                "continuous": True,
                "max_pixel_coverage": 2,
                "erase_radius_max": 5,
            },
            description="Chaotic scribble — short erratic steps, long wandering chains",
        ),
        # --- Edge-focused presets ---
        Preset(
            name="Edge Trace",
            params={
                **_base,
                "line_density": 1.0,
                "line_max_limit": 5000,
                "angle_tests": 16,
                "line_length_px": 18,
                "edge_power": 60.0,
                "directionality": 25.0,
                "straight_bias": 0.7,
                "squiggle_max_length": 60,
                "squiggle_max_deviation": 12.0,
                "unsharp_amount": 4,
                "chain_max": 20,
                "long_line_bias": 0.3,
                "max_pixel_coverage": 2,
            },
            description="Lines concentrate on edges — strong unsharp mask, tight squiggle deviation",
        ),
        # --- Hybrid presets ---
        Preset(
            name="Hybrid Portrait",
            params={
                **_base,
                "mark_mode": "Hybrid",
                "line_density": 1.5,
                "line_max_limit": 6000,
                "angle_tests": 12,
                "line_length_px": 15,
                "directionality": 20.0,
                "edge_power": 15.0,
                "straight_bias": 0.7,
                "unsharp_amount": 3,
                "chain_max": 15,
                "max_pixel_coverage": 2,
                "squiggle_max_length": 30,
            },
            description="Mixed mark types — squiggles on edges, dots in flat areas, lines in gradients",
        ),
        Preset(
            name="Hybrid Dense",
            params={
                **_base,
                "mark_mode": "Hybrid",
                "line_density": 2.0,
                "line_max_limit": 10000,
                "angle_tests": 12,
                "line_length_px": 12,
                "max_pixel_coverage": 3,
                "max_overlap_ratio": 0.65,
                "straight_bias": 0.5,
                "long_line_bias": 0.2,
                "chain_max": 12,
                "squiggle_max_length": 20,
            },
            description="Dense hybrid — heavy coverage with varied mark types",
        ),
    ]
