"""Google Fonts catalog browsing and font downloading for Plottter.

This module provides:

- :func:`get_google_fonts_catalog` — Load the bundled catalog of Google Fonts
  metadata (family, category, styles, download URL).
- :func:`search_google_fonts` — Case-insensitive search across the catalog,
  optionally filtered by category.
- :func:`download_google_font` — Download a Google Font TTF to the local
  disk cache (``~/.plottter/fonts/google/``).

The bundled catalog (``google_fonts_catalog.json``) contains 1 900+ font
families and is committed to the repository.  It is generated by running::

    python scripts/fetch_google_fonts_catalog.py

When a font is downloaded, it is cached to disk so subsequent calls are
instant (no network request).  The discovery module
(:mod:`plottter.fonts.discovery`) automatically includes the Google Fonts
cache directory when scanning for available fonts, so downloaded fonts appear
alongside system fonts everywhere in the application.

Downloading uses the Google Fonts CSS2 API to resolve the current TTF URL for
each font — no API key is required.
"""

from __future__ import annotations

import json
import re
import urllib.request
import urllib.parse
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

# ---------------------------------------------------------------------------
# GoogleFontInfo dataclass
# ---------------------------------------------------------------------------


@dataclass
class GoogleFontInfo:
    """Metadata for a single Google Fonts family."""

    family: str
    """Font family name, e.g. ``"Roboto"``."""

    category: str
    """Category string: ``"serif"``, ``"sans-serif"``, ``"display"``,
    ``"handwriting"``, or ``"monospace"``."""

    styles: list[str]
    """Normalised list of available styles, e.g. ``["regular", "italic",
    "bold", "500"]``."""

    download_url: str
    """Google Fonts CSS2 URL for the regular weight — used internally by
    :func:`download_google_font` to resolve the actual TTF file URL."""


# ---------------------------------------------------------------------------
# Catalog
# ---------------------------------------------------------------------------

_CATALOG_PATH = Path(__file__).parent / "google_fonts_catalog.json"

# In-memory cache of the catalog (loaded once per process)
_catalog: list[GoogleFontInfo] | None = None


def get_google_fonts_catalog() -> list[GoogleFontInfo]:
    """Return the bundled list of Google Fonts families.

    The catalog is loaded from ``google_fonts_catalog.json`` and cached in
    memory.  The list is sorted alphabetically by family name.

    Returns
    -------
    list[GoogleFontInfo]
        All catalogued Google Font families.  The list is never empty on a
        correctly installed package (it contains 1 900+ entries).
    """
    global _catalog
    if _catalog is not None:
        return _catalog

    raw: list[dict] = json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    _catalog = [
        GoogleFontInfo(
            family=entry["family"],
            category=entry.get("category", ""),
            styles=entry.get("styles", []),
            download_url=entry.get("download_url", ""),
        )
        for entry in raw
    ]
    return _catalog


def search_google_fonts(
    query: str, *, category: str | None = None
) -> list[GoogleFontInfo]:
    """Search the Google Fonts catalog by family name.

    Parameters
    ----------
    query:
        Case-insensitive substring to search for in family names.
        An empty string returns all fonts (optionally filtered by category).
    category:
        If given, restrict results to this category (e.g. ``"monospace"``).
        The comparison is case-insensitive.

    Returns
    -------
    list[GoogleFontInfo]
        Matching font families in alphabetical order.
    """
    catalog = get_google_fonts_catalog()
    q = query.lower()
    cat = category.lower() if category else None

    results: list[GoogleFontInfo] = []
    for font in catalog:
        if q and q not in font.family.lower():
            continue
        if cat and font.category.lower() != cat:
            continue
        results.append(font)
    return results


# ---------------------------------------------------------------------------
# Download
# ---------------------------------------------------------------------------

_CACHE_DIR = Path.home() / ".plottter" / "fonts" / "google"

# User-agent that causes Google Fonts CSS API to return direct TTF URLs
# rather than WOFF2 (which requires the brotli library to decode).
_TTF_USER_AGENT = "Android 2.2; en-us; GT-I5500 Build/FROYO"

# Regex to extract TTF URLs from the Google Fonts CSS response
_TTF_URL_RE = re.compile(
    r"url\((https://fonts\.gstatic\.com/[^\)]+\.ttf)\)"
)


def _resolve_ttf_url(family: str, weight: str = "400") -> str:
    """Resolve the direct gstatic TTF URL for a Google Font via the CSS2 API.

    Parameters
    ----------
    family:
        Font family name (e.g. ``"Roboto"``).
    weight:
        Numeric weight string (e.g. ``"400"`` for regular, ``"700"`` for bold).

    Returns
    -------
    str
        Direct ``fonts.gstatic.com`` URL for the TTF file.

    Raises
    ------
    ValueError
        If no TTF URL can be found in the API response.
    RuntimeError
        If the CSS2 API request fails.
    """
    encoded = urllib.parse.quote(family)
    css_url = (
        f"https://fonts.googleapis.com/css2?family={encoded}:wght@{weight}&display=swap"
    )
    req = urllib.request.Request(
        css_url,
        headers={"User-Agent": _TTF_USER_AGENT},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            css = resp.read().decode("utf-8")
    except Exception as exc:
        raise RuntimeError(
            f"Failed to fetch CSS for {family!r} from Google Fonts: {exc}"
        ) from exc

    match = _TTF_URL_RE.search(css)
    if not match:
        raise ValueError(
            f"Could not find a TTF URL for {family!r} (weight {weight}) "
            f"in the Google Fonts CSS response.\n"
            f"CSS snippet: {css[:400]}"
        )
    return match.group(1)


def download_google_font(
    family: str,
    style: str = "regular",
    *,
    cache_dir: Path | str | None = None,
    progress_callback: Callable[[int, int], None] | None = None,
) -> str:
    """Download a Google Font TTF file to the local cache directory.

    The font is fetched from ``fonts.gstatic.com`` via the Google Fonts CSS2
    API and cached to ``~/.plottter/fonts/google/{family}-{style}.ttf``.
    If the file already exists in the cache, the download is skipped and the
    cached path is returned immediately.

    The cache directory is automatically scanned by
    :func:`plottter.fonts.discovery.discover_system_fonts`, so downloaded
    fonts appear alongside system fonts in the application.

    Parameters
    ----------
    family:
        Font family name exactly as listed in the catalog (e.g. ``"Roboto"``).
    style:
        Style name: ``"regular"``, ``"italic"``, ``"bold"``, or a numeric
        weight string like ``"500"`` or ``"700italic"``.  Defaults to
        ``"regular"``.
    cache_dir:
        Directory to save the font file.  Defaults to
        ``~/.plottter/fonts/google/``.
    progress_callback:
        Optional callable that receives ``(bytes_downloaded, total_bytes)``
        during the download.  ``total_bytes`` may be 0 if the server does not
        send ``Content-Length``.

    Returns
    -------
    str
        Absolute path to the cached TTF file.

    Raises
    ------
    ValueError
        If no TTF URL is available for the requested family/style.
    RuntimeError
        If the download fails (network error, HTTP error, etc.).
    """
    dest_dir = Path(cache_dir) if cache_dir is not None else _CACHE_DIR
    dest_dir.mkdir(parents=True, exist_ok=True)

    # Reject family/style names that contain path-traversal characters.
    # We check BEFORE any transformation so that inputs like "../attack" are
    # rejected outright rather than silently sanitised to "attack".
    if "/" in family or "\\" in family or ".." in family:
        raise ValueError(f"Invalid font family name: {family!r}")
    if "/" in style or "\\" in style or ".." in style:
        raise ValueError(f"Invalid font style name: {style!r}")

    # Build the cache filename: replace spaces with hyphens.
    safe_family = family.replace(" ", "-")
    safe_style = style
    dest = dest_dir / f"{safe_family}-{safe_style}.ttf"

    # Cache hit — skip download
    if dest.exists():
        return str(dest)

    # Map style name to numeric weight for the CSS2 API
    weight = _style_to_weight(style)

    # Resolve the direct TTF URL
    ttf_url = _resolve_ttf_url(family, weight)

    # Download the file
    req = urllib.request.Request(
        ttf_url,
        headers={"User-Agent": _TTF_USER_AGENT},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            total = int(resp.headers.get("Content-Length") or 0)
            data = bytearray()
            chunk_size = 8192
            while True:
                chunk = resp.read(chunk_size)
                if not chunk:
                    break
                data.extend(chunk)
                if progress_callback:
                    progress_callback(len(data), total)
    except Exception as exc:
        raise RuntimeError(
            f"Failed to download {family!r} from {ttf_url!r}: {exc}"
        ) from exc

    dest.write_bytes(bytes(data))
    return str(dest)


def _style_to_weight(style: str) -> str:
    """Convert a normalised style name to a numeric weight string.

    Used to construct the Google Fonts CSS2 API URL.

    Examples
    --------
    >>> _style_to_weight("regular")
    '400'
    >>> _style_to_weight("bold")
    '700'
    >>> _style_to_weight("500")
    '500'
    >>> _style_to_weight("700italic")
    '700'
    """
    # Strip italic suffix if present
    style_clean = style.replace("italic", "").strip()

    _MAP = {
        "": "400",
        "regular": "400",
        "bold": "700",
        "thin": "100",
        "light": "300",
        "medium": "500",
        "semibold": "600",
        "extrabold": "800",
        "black": "900",
    }
    if style_clean in _MAP:
        return _MAP[style_clean]
    # Assume it's already a numeric weight
    if style_clean.isdigit():
        return style_clean
    return "400"
